<script setup lang="ts">
import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, CircleAlert, Coins, FileCheck2, FileText, RefreshCw, Users, Clock3 } from '@lucide/vue'

definePageMeta({ middleware: 'auth', ssr: false })

interface Metric { key: string; label: string; value: number; format: 'number' | 'currency' | 'percent' | 'days'; change: number | null; previousValue: number | null }
interface TrendPoint { label: string; registered: number; signed: number; commercial: number; verification: number; verified: number; appointments: number }
interface Breakdown { key: string; label: string; value: number }
interface WorkItem { id: string; contractId: string; contractNumber: string; holderName: string; holderDni: string; program: string; advisorName: string; status: string; location: string; updatedAt: string; queueEnteredAt: string | null; appointmentAt: string | null; appointmentType: string | null; observation: string | null; queueReason?: string | null; documentCount: number; missingDocuments: string[] }
interface Advisor { id: string; name: string; total: number; signed: number; cancelled: number; contracted: number; signingRate: number }
interface DashboardData { role: string; scope: string; period: number; summary: Record<string, number>; metrics: Metric[]; trend: TrendPoint[]; contractStatusBreakdown: Breakdown[]; expedientStatusBreakdown: Breakdown[]; locationBreakdown: Array<{ location: string; status: string; value: number }>; priorities: Array<{ key: string; label: string; value: number; href: string }>; advisors: Advisor[]; workQueue: WorkItem[] }

const { user, verifyToken } = useAuth()
const data = ref<DashboardData | null>(null)
const loading = ref(true)
const error = ref('')
const period = ref(30)
const queueStatus = ref('')
const nf = new Intl.NumberFormat('es-PE')
const money = (value: number) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN', maximumFractionDigits: 0 }).format(value || 0)
const formatValue = (metric: Metric, value = metric.value) => metric.format === 'currency' ? money(value) : metric.format === 'percent' ? `${nf.format(value)}%` : metric.format === 'days' ? `${nf.format(value)} d` : nf.format(value)
const firstName = computed(() => user.value?.name?.split(' ')[0] || 'bienvenido')
const statusLabels: Record<string, string> = { REVISION: 'En revisión', FIRMADO: 'Firmado', ANULADO: 'Anulado', CREADO: 'Por revisar', REBOTADO: 'Rebotado', AGENDADO: 'Cita programada', OBSERVADO: 'Con observaciones', VERIFICADO: 'Verificado', ANULACION_PENDIENTE: 'Firma pendiente' }
const statusTone: Record<string, string> = { REVISION: 'pending', FIRMADO: 'signed', ANULADO: 'neutral', CREADO: 'review', REBOTADO: 'danger', AGENDADO: 'review', OBSERVADO: 'pending', VERIFICADO: 'signed', ANULACION_PENDIENTE: 'pending' }
const fmtStatus = (key: string) => statusLabels[key] || key.replaceAll('_', ' ')
const metricIcons = [Users, FileText, Clock3, Coins]
const chartSeries = computed(() => ['asistente_comercial', 'verificador'].includes(data.value?.role || '') ? [{ key: 'commercial', label: 'Recibidos', color: '#1769e0' }, { key: 'verification', label: 'Derivados', color: '#d71943' }] : [{ key: 'registered', label: 'Matrículas', color: '#1769e0' }, { key: 'signed', label: 'Contratos firmados', color: '#d71943' }])
const chartPoints = computed(() => {
  const points = data.value?.trend || []
  const max = Math.max(...points.flatMap((point) => chartSeries.value.map((series) => Number(point[series.key as keyof TrendPoint]) || 0)), 1)
  return points.map((point, index) => ({ ...point, x: points.length > 1 ? 34 + index * (650 / (points.length - 1)) : 34, values: chartSeries.value.map((series) => ({ ...series, value: Number(point[series.key as keyof TrendPoint]) || 0, y: 204 - ((Number(point[series.key as keyof TrendPoint]) || 0) / max) * 165 })) }))
})
const linePath = (seriesIndex: number) => chartPoints.value.map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.values[seriesIndex]?.y ?? 204}`).join(' ')
const areaPath = (seriesIndex: number) => `${linePath(seriesIndex)} L ${chartPoints.value.at(-1)?.x || 684} 204 L ${chartPoints.value[0]?.x || 34} 204 Z`
const chartMax = computed(() => Math.max(...(data.value?.trend || []).flatMap((point) => chartSeries.value.map((series) => Number(point[series.key as keyof TrendPoint]) || 0)), 1))
const doughnutTotal = computed(() => (data.value?.contractStatusBreakdown || []).reduce((total, segment) => total + segment.value, 0))
const doughnutStyle = computed(() => { let cursor = 0; const colors = ['#d71943', '#9fb2d0', '#6da5f0', '#c9d6ea']; return (data.value?.contractStatusBreakdown || []).map((segment, index) => { const start = cursor; cursor += doughnutTotal.value ? segment.value / doughnutTotal.value * 100 : 0; return `${colors[index % colors.length]} ${start}% ${cursor}%` }).join(', ') || '#e5eaf2 0 100%' })
const stageGroups = computed(() => { const locations = [{ key: 'ASESOR', label: 'Admisión' }, { key: 'ASISTENTE_COMERCIAL', label: 'Finanzas' }, { key: 'SUPERVISOR', label: 'Legal' }, { key: 'VERIFICACION', label: 'Firma de contrato' }]; return locations.map((location) => ({ ...location, value: (data.value?.locationBreakdown || []).filter((row) => row.location === location.key && row.status !== 'VERIFICADO').reduce((sum, row) => sum + row.value, 0) })).filter((stage) => stage.value > 0) })
const maxStage = computed(() => Math.max(...stageGroups.value.map((stage) => stage.value), 1))
const filteredQueue = computed(() => (data.value?.workQueue || []).filter((item) => !queueStatus.value || item.status === queueStatus.value).slice(0, 5))
const queueStatuses = computed(() => [...new Set((data.value?.workQueue || []).map((item) => item.status))])
const changeIsGood = (metric: Metric) => ['pendingSignatures', 'commercialReturned', 'overdueAppointments'].includes(metric.key) ? (metric.change || 0) <= 0 : (metric.change || 0) >= 0
const ageDays = (item: WorkItem) => Math.max(0, Math.floor((Date.now() - new Date(item.queueEnteredAt || item.updatedAt).getTime()) / 86400000))
const loadDashboard = async () => { loading.value = true; error.value = ''; try { data.value = await $fetch<DashboardData>('/api/dashboard', { credentials: 'include', query: { period: period.value } }) } catch (err: any) { error.value = err?.data?.statusMessage || 'No pudimos cargar el dashboard.' } finally { loading.value = false } }
onMounted(async () => { if (!user.value) await verifyToken(); await loadDashboard() })
</script>

<template>
  <div class="dashboard-page">
    <AppHeader title="Dashboard" subtitle="Centro de operaciones de matrículas" />
    <main class="dashboard-content">
      <section class="dashboard-intro">
        <div><h1>Hola, {{ firstName }}</h1><p>Aquí tienes el resumen de la operación de matrículas y contratos.</p></div>
        <div class="period-control"><span>Periodo</span><label for="dashboard-period" class="sr-only">Periodo</label><select id="dashboard-period" v-model="period" @change="loadDashboard"><option :value="7">Últimos 7 días</option><option :value="30">Últimos 30 días</option><option :value="90">Últimos 90 días</option><option :value="365">Último año</option></select><CalendarDays class="period-icon" /><ChevronDown class="period-chevron" /></div>
      </section>

      <div v-if="error" class="dashboard-error" role="alert"><span>{{ error }}</span><button type="button" @click="loadDashboard"><RefreshCw :size="15" /> Reintentar</button></div>
      <div v-if="loading" class="dashboard-loading"><UiSkeleton v-for="item in 8" :key="item" class="rounded-lg" :class="item < 5 ? 'h-28' : 'h-64'" /></div>
      <template v-else-if="data">
        <section class="metric-grid" aria-label="Indicadores principales">
          <article v-for="(metric, index) in data.metrics.slice(0, 4)" :key="metric.key" class="metric-card"><span class="metric-icon" :class="`metric-icon-${index}`"><component :is="metricIcons[index] || FileText" :size="27" /></span><div class="metric-copy"><p>{{ metric.label }}</p><div class="metric-value-row"><strong>{{ formatValue(metric) }}</strong><span v-if="metric.change !== null" :class="changeIsGood(metric) ? 'change-good' : 'change-bad'"><ArrowUpRight v-if="metric.change >= 0" :size="14" /><ArrowDownRight v-else :size="14" /> {{ metric.change > 0 ? '+' : '' }}{{ metric.change }}%</span></div><small>{{ metric.previousValue !== null ? `vs. periodo anterior (${formatValue(metric, metric.previousValue)})` : 'Casos actuales que requieren seguimiento' }}</small></div></article>
        </section>

        <section class="dashboard-middle">
          <article class="panel trend-panel"><div class="panel-heading"><div><h2>Evolución de matrículas y firmas</h2><p>Comparativo mensual del número de matrículas vs. contratos firmados.</p></div><select aria-label="Agrupación de la gráfica"><option>Mensual</option><option>Semanal</option></select></div><div class="chart-wrap"><div class="chart-y-labels"><span>{{ chartMax }}</span><span>{{ Math.round(chartMax * .75) }}</span><span>{{ Math.round(chartMax * .5) }}</span><span>{{ Math.round(chartMax * .25) }}</span><span>0</span></div><svg class="trend-chart" viewBox="0 0 720 250" role="img" aria-label="Evolución de matrículas y firmas"><defs><linearGradient id="blueArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#1769e0" stop-opacity=".12" /><stop offset="1" stop-color="#1769e0" stop-opacity="0" /></linearGradient></defs><g class="chart-grid"><line v-for="y in [39,80,121,162,204]" :key="y" x1="34" :y1="y" x2="684" :y2="y" /><line v-for="x in chartPoints" :key="x.x" :x1="x.x" y1="39" :x2="x.x" y2="204" /></g><path v-if="chartPoints.length" :d="areaPath(0)" fill="url(#blueArea)" /><path v-for="(series, index) in chartSeries" :key="series.key" :d="linePath(index)" fill="none" :stroke="series.color" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" /><template v-for="point in chartPoints" :key="point.x"><circle v-for="series in point.values" :key="series.key" :cx="point.x" :cy="series.y" r="3.5" :fill="series.color" stroke="white" stroke-width="2" /></template></svg><div class="chart-x-labels"><span v-for="point in chartPoints" :key="point.x">{{ point.label }}</span></div></div><div class="chart-legend"><span v-for="series in chartSeries" :key="series.key"><i :style="{ background: series.color }" />{{ series.label }}</span></div></article>

          <article class="panel status-panel"><div class="panel-heading"><div><h2>Estado de contratos</h2><p>Distribución por estado actual.</p></div></div><div class="donut-wrap"><div class="donut" :style="{ background: `conic-gradient(${doughnutStyle})` }"><div><strong>{{ nf.format(doughnutTotal) }}</strong><span>contratos<br />totales</span></div></div></div><div class="status-list"><div v-for="(segment, index) in data.contractStatusBreakdown" :key="segment.key"><span><i class="status-dot" :class="`dot-${index}`" />{{ fmtStatus(segment.key) }}</span><b>{{ nf.format(segment.value) }}</b><small>{{ doughnutTotal ? Math.round(segment.value / doughnutTotal * 100) : 0 }}%</small></div></div></article>

          <div class="side-panels"><article class="panel stages-panel"><div class="panel-heading"><div><h2>Expedientes por etapa responsable</h2><p>Número de expedientes en cada etapa del proceso.</p></div></div><div class="stage-list"><div v-for="stage in stageGroups" :key="stage.key"><span>{{ stage.label }}</span><div><i :style="{ width: `${Math.max(stage.value / maxStage * 100, 3)}%` }" /></div><b>{{ nf.format(stage.value) }}</b></div><p v-if="!stageGroups.length" class="empty-copy">Sin expedientes registrados.</p></div></article><article class="panel advisors-panel"><div class="panel-heading"><div><h2>Rendimiento de asesores</h2><p>Matrículas, firmas, tasa de conversión y valor contratado.</p></div><NuxtLink to="/matriculas">Ver todos <ArrowRight :size="14" /></NuxtLink></div><div class="advisor-table"><div class="advisor-row advisor-head"><span>Asesor</span><span>Matrículas</span><span>Firmas</span><span>Conversión</span><span>Valor contratado</span></div><div v-for="advisor in [...data.advisors].sort((a, b) => b.signed - a.signed).slice(0, 5)" :key="advisor.id" class="advisor-row"><span class="advisor-name"><i>{{ advisor.name.split(' ').map((name) => name[0]).slice(0, 2).join('') }}</i>{{ advisor.name }}</span><span>{{ advisor.total }}</span><span>{{ advisor.signed }}</span><span>{{ advisor.signingRate }}%</span><span>{{ money(advisor.contracted) }}</span></div><p v-if="!data.advisors.length" class="empty-copy">No hay asesores para comparar.</p></div></article></div>
        </section>

        <section class="panel queue-panel"><div class="queue-heading"><div><h2>Cola de trabajo</h2><p>Matrículas con contrato pendiente o en proceso, ordenadas por mayor tiempo de espera.</p></div><div class="queue-actions"><select v-model="queueStatus" aria-label="Filtrar cola por estado"><option value="">Todos los estados</option><option v-for="status in queueStatuses" :key="status" :value="status">{{ fmtStatus(status) }}</option></select><NuxtLink to="/matriculas">Ver cola completa <ArrowRight :size="15" /></NuxtLink></div></div><div class="queue-scroll"><table><thead><tr><th>Estudiante / titular</th><th>DNI</th><th>Programa</th><th>Asesor asignado</th><th>Estado actual</th><th>Días en espera</th><th>Última actividad</th><th>Acciones</th></tr></thead><tbody><tr v-for="item in filteredQueue" :key="item.id"><td><strong>{{ item.holderName }}</strong></td><td>{{ item.holderDni }}</td><td>{{ item.program }}</td><td>{{ item.advisorName }}</td><td><span class="status-pill" :class="statusTone[item.status] || 'neutral'">{{ fmtStatus(item.status) }}</span></td><td>{{ ageDays(item) }}</td><td>{{ new Date(item.updatedAt).toLocaleDateString('es-PE', { day: '2-digit', month: 'short', year: 'numeric' }) }}</td><td><NuxtLink :to="item.location === 'ASESOR' ? `/matricula/${item.contractId}` : `/expedientes/${item.id}`">Ver detalle <ArrowRight :size="14" /></NuxtLink></td></tr></tbody></table><div v-if="!filteredQueue.length" class="queue-empty"><CircleAlert :size="18" /> No hay casos pendientes para mostrar.</div></div></section>
      </template>
      <div v-else-if="!error" class="empty-state"><p>No hay información para mostrar</p><button type="button" @click="loadDashboard">Recargar</button></div>
    </main>
  </div>
</template>

<style scoped>
.dashboard-page { min-height: 100dvh; background: #f4f7fb; color: #10234b; }
.dashboard-content { max-width: 1680px; margin: 0 auto; padding: 24px 28px 36px; }
.dashboard-intro, .panel-heading, .queue-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 18px; }
.dashboard-intro { align-items: center; margin-bottom: 20px; }
.dashboard-intro h1 { margin: 0; color: #071a4d; font-size: 27px; line-height: 1.1; letter-spacing: -.04em; }
.dashboard-intro p, .panel-heading p, .queue-heading p { margin: 5px 0 0; color: #657695; font-size: 13px; }
.period-control { position: relative; display: flex; align-items: center; gap: 10px; color: #657695; font-size: 12px; }
.period-control select, .panel-heading select, .queue-actions select { height: 34px; border: 1px solid #d6deeb; border-radius: 6px; background: white; color: #23375e; padding: 0 31px 0 35px; font-size: 12px; outline: none; }
.period-icon { position: absolute; right: 95px; width: 15px; color: #53688e; pointer-events: none; }.period-chevron { position: absolute; right: 9px; width: 14px; pointer-events: none; }
.dashboard-error { display: flex; justify-content: space-between; align-items: center; border: 1px solid #f3c4cb; border-radius: 7px; padding: 12px 15px; margin-bottom: 16px; background: #fff4f5; color: #8b152c; font-size: 13px; }.dashboard-error button, .empty-state button { display: inline-flex; align-items: center; gap: 6px; border: 1px solid #c8102e; border-radius: 5px; padding: 7px 11px; color: #c8102e; background: white; font-size: 12px; cursor: pointer; }
.dashboard-loading { display: grid; grid-template-columns: repeat(4, 1fr); gap: 13px; }.dashboard-loading > :nth-child(n+5) { grid-column: span 2; }
.metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 13px; margin-bottom: 13px; }.metric-card, .panel { border: 1px solid #e1e7f0; border-radius: 7px; background: white; box-shadow: 0 2px 8px rgba(28, 50, 83, .025); }.metric-card { display: flex; align-items: center; gap: 16px; min-height: 116px; padding: 17px; }.metric-icon { display: grid; place-items: center; width: 55px; height: 55px; flex: 0 0 auto; border-radius: 10px; }.metric-icon-0, .metric-icon-1 { background: #edf5ff; color: #1670e8; }.metric-icon-2 { background: #fff0f3; color: #d71943; }.metric-icon-3 { background: #fff6e7; color: #e58b09; }.metric-copy { min-width: 0; }.metric-copy p { margin: 0; color: #293c62; font-size: 13px; font-weight: 600; }.metric-value-row { display: flex; align-items: baseline; gap: 10px; margin-top: 2px; }.metric-value-row strong { color: #081c52; font-size: 25px; letter-spacing: -.035em; }.metric-value-row span { display: inline-flex; align-items: center; font-size: 12px; font-weight: 700; }.change-good { color: #139a6b; }.change-bad { color: #d71943; }.metric-copy small { display: block; overflow: hidden; margin-top: 2px; color: #8491a7; font-size: 11px; text-overflow: ellipsis; white-space: nowrap; }
.dashboard-middle { display: grid; grid-template-columns: minmax(0, 1.62fr) minmax(220px, .66fr) minmax(320px, 1.15fr); gap: 13px; align-items: stretch; }.panel { overflow: hidden; }.panel-heading { padding: 15px 16px 7px; }.panel-heading h2, .queue-heading h2 { margin: 0; color: #102553; font-size: 16px; letter-spacing: -.025em; }.panel-heading a, .queue-actions a, .queue-panel a { display: inline-flex; align-items: center; gap: 5px; color: #0757ce; font-size: 12px; font-weight: 600; text-decoration: none; white-space: nowrap; }.trend-panel { min-width: 0; }.trend-panel .panel-heading select { padding: 0 29px 0 11px; }.chart-wrap { position: relative; padding: 12px 17px 0 48px; }.trend-chart { display: block; width: 100%; height: 235px; overflow: visible; }.chart-grid line { stroke: #e5eaf1; stroke-width: 1; }.chart-y-labels { position: absolute; top: 21px; bottom: 27px; left: 16px; display: flex; flex-direction: column; justify-content: space-between; color: #71809b; font-size: 10px; }.chart-x-labels { display: flex; justify-content: space-between; padding: 1px 2px 0; color: #71809b; font-size: 10px; }.chart-legend { display: flex; justify-content: center; gap: 26px; padding: 16px 12px 17px; color: #20335a; font-size: 12px; }.chart-legend span { display: inline-flex; align-items: center; gap: 7px; }.chart-legend i { width: 10px; height: 10px; border-radius: 50%; }.status-panel { min-width: 0; }.donut-wrap { display: grid; place-items: center; padding: 10px 0 6px; }.donut { display: grid; place-items: center; width: 170px; height: 170px; border-radius: 50%; }.donut::before { content: ''; position: absolute; width: 112px; height: 112px; border-radius: 50%; background: white; }.donut > div { position: relative; z-index: 1; text-align: center; }.donut strong { display: block; color: #091d52; font-size: 21px; }.donut span { display: block; margin-top: 3px; color: #657695; font-size: 12px; line-height: 1.3; }.status-list { padding: 6px 16px 16px; }.status-list > div { display: grid; grid-template-columns: minmax(0, 1fr) 40px 30px; align-items: center; gap: 5px; padding: 4px 0; color: #25385f; font-size: 12px; }.status-list span { display: flex; align-items: center; gap: 8px; }.status-list b { text-align: right; font-weight: 600; }.status-list small { text-align: right; color: #53688e; }.status-dot { width: 10px; height: 10px; border-radius: 50%; }.dot-0 { background: #d71943; }.dot-1 { background: #9fb2d0; }.dot-2 { background: #6da5f0; }.dot-3 { background: #c9d6ea; }
.side-panels { display: grid; gap: 13px; min-width: 0; }.stages-panel { min-height: 185px; }.stage-list { padding: 8px 16px 16px; }.stage-list > div { display: grid; grid-template-columns: 100px minmax(0, 1fr) 30px; align-items: center; gap: 9px; margin: 12px 0; color: #273b61; font-size: 12px; }.stage-list > div > div { height: 15px; overflow: hidden; border-radius: 3px; background: #f0f3f8; }.stage-list i { display: block; height: 100%; border-radius: 3px; background: #2878df; }.stage-list b { text-align: right; color: #162d5c; font-size: 12px; }.empty-copy { margin: 10px 0; color: #8390a5; font-size: 12px; }.advisors-panel { min-height: 239px; }.advisor-table { overflow-x: auto; padding-bottom: 5px; }.advisor-row { display: grid; grid-template-columns: minmax(125px, 1.45fr) .55fr .55fr .7fr 1.1fr; min-width: 430px; align-items: center; border-top: 1px solid #edf0f5; padding: 7px 15px; color: #283b61; font-size: 11px; }.advisor-head { border-top: 1px solid #e7ebf2; background: #f5f7fa; color: #506382; font-size: 10px; font-weight: 600; }.advisor-row > span:not(:first-child) { text-align: right; }.advisor-name { display: flex; align-items: center; gap: 7px; white-space: nowrap; }.advisor-name i { display: grid; place-items: center; width: 23px; height: 23px; border-radius: 50%; background: #f6c86c; color: #68430f; font-style: normal; font-size: 9px; font-weight: 700; }.advisor-row:nth-child(3n) .advisor-name i { background: #a8c8f5; color: #1d508f; }.advisor-row:nth-child(4n) .advisor-name i { background: #f2a5b8; color: #8b1b3d; }
.queue-panel { margin-top: 13px; }.queue-heading { align-items: center; padding: 15px 17px 13px; }.queue-actions { display: flex; align-items: center; gap: 18px; }.queue-actions select { min-width: 160px; padding: 0 11px; }.queue-scroll { overflow-x: auto; padding: 0 16px 10px; }.queue-scroll table { width: 100%; min-width: 990px; border-collapse: collapse; font-size: 11px; }.queue-scroll th { padding: 8px 12px; background: #f0f3f8; color: #22365d; text-align: left; font-size: 10px; font-weight: 700; white-space: nowrap; }.queue-scroll td { border-bottom: 1px solid #e6eaf1; padding: 8px 12px; color: #25385f; white-space: nowrap; }.queue-scroll td strong { color: #152d5b; font-weight: 600; }.queue-scroll td:last-child a { color: #0757ce; }.status-pill { display: inline-flex; border-radius: 999px; padding: 4px 9px; font-size: 10px; font-weight: 600; }.status-pill.signed { background: #dff6ed; color: #147550; }.status-pill.pending { background: #fff0c9; color: #8d5e06; }.status-pill.review { background: #dceaff; color: #1e5bb2; }.status-pill.danger { background: #ffe0e6; color: #a91736; }.status-pill.neutral { background: #edf0f5; color: #53617a; }.queue-empty { display: flex; justify-content: center; align-items: center; gap: 7px; padding: 32px; color: #75839b; font-size: 12px; }.empty-state { padding: 50px; text-align: center; color: #657695; }.empty-state button { margin-top: 12px; }
@media (max-width: 1250px) { .dashboard-middle { grid-template-columns: minmax(0, 1.5fr) minmax(220px, .8fr); }.side-panels { grid-column: 1 / -1; grid-template-columns: 1fr 1fr; }.metric-card { padding: 14px; gap: 11px; } }
@media (max-width: 850px) { .dashboard-content { padding: 18px 16px 28px; }.dashboard-intro { align-items: flex-start; flex-direction: column; }.metric-grid { grid-template-columns: repeat(2, 1fr); }.dashboard-middle { grid-template-columns: 1fr; }.side-panels { grid-template-columns: 1fr; }.queue-heading { align-items: flex-start; flex-direction: column; }.queue-actions { width: 100%; justify-content: space-between; } }
@media (max-width: 520px) { .metric-grid { grid-template-columns: 1fr; }.metric-card { min-height: 100px; }.period-control { width: 100%; justify-content: space-between; }.period-control select { flex: 1; }.period-icon { right: 59px; }.dashboard-loading { grid-template-columns: 1fr; }.dashboard-loading > :nth-child(n+5) { grid-column: auto; }.chart-wrap { padding-left: 39px; padding-right: 8px; }.chart-y-labels { left: 9px; }.chart-legend { gap: 12px; flex-wrap: wrap; }.queue-actions { align-items: flex-start; flex-direction: column; gap: 11px; } }
</style>
