export type Ubigeo = Record<string, Record<string, string[]>>

// Catálogo usado por el formulario antiguo. La relación es Departamento -> Provincia -> Distrito.
export const ubigeoPeru: Ubigeo = {
  Amazonas: { Chachapoyas: ['Chachapoyas', 'Asunción', 'Balsas', 'Leymebamba', 'Maino'], Bagua: ['Bagua', 'Aramango', 'Copallin', 'Imaza', 'La Peca'], Bongará: ['Jumbilla', 'Florida', 'Jazan', 'Shipasbamba'], Condorcanqui: ['Nieva', 'El Cenepa', 'Río Santiago'], Luya: ['Lamud', 'Camporredondo', 'Colcamar', 'Luya', 'Ocalli'], 'Rodríguez de Mendoza': ['San Nicolás', 'Cohechan', 'Omia', 'Totora'], Utcubamba: ['Bagua Grande', 'Cajaruro', 'Cumba', 'Lonya Grande'] },
  Ancash: { Huaraz: ['Huaraz', 'Independencia', 'Jangas', 'Tarica'], Aija: ['Aija', 'Coris', 'Huacllan'], 'Antonio Raymondi': ['Llamellin', 'Aczo', 'Chaccho'], Asunción: ['Chacas', 'Acochaca'], Bolognesi: ['Chiquián', 'Aquia', 'Huallanca'], Carhuaz: ['Carhuaz', 'Anta', 'Marcara', 'Shilla'], 'Carlos Fermín Fitzcarrald': ['San Luis', 'Yauya'], Casma: ['Casma', 'Buenavista Alta', 'Comandante Noel'], Corongo: ['Corongo', 'Aco', 'Yupan'], Huari: ['Huari', 'Chavin de Huantar', 'San Marcos'], Huarmey: ['Huarmey', 'Culebras', 'Huayan'], Huaylas: ['Caraz', 'Huallanca', 'Huata', 'Pueblo Libre'], 'Mariscal Luzuriaga': ['Piscobamba', 'Casca', 'Lucma'], Ocros: ['Ocros', 'Cajamarquilla', 'San Pedro'], Pallasca: ['Cabana', 'Conchucos', 'Pallasca'], Pomabamba: ['Pomabamba', 'Huayllan', 'Parobamba'], Recuay: ['Recuay', 'Catac', 'Ticapampa'], Santa: ['Chimbote', 'Nuevo Chimbote', 'Coishco', 'Moro', 'Nepeña', 'Santa'], Sihuas: ['Sihuas', 'Cashapampa', 'Ragash'], Yungay: ['Yungay', 'Cascapara', 'Mancos', 'Yanama'] },
  Apurímac: { Abancay: ['Abancay', 'Chacoche', 'Curahuasi', 'Tamburco'], Andahuaylas: ['Andahuaylas', 'San Jerónimo', 'Talavera', 'Pacucha'], Antabamba: ['Antabamba', 'Huaquirca', 'Sabaino'], Aymaraes: ['Chalhuanca', 'Capaya', 'Cotaruse'], Cotabambas: ['Tambobamba', 'Coyllurqui', 'Haquira'], Chincheros: ['Chincheros', 'Anco_Huallo', 'Ocobamba'], Grau: ['Chuquibambilla', 'Curpahuasi', 'Vilcabamba'] },
  Arequipa: { Arequipa: ['Arequipa', 'Alto Selva Alegre', 'Cayma', 'Cerro Colorado', 'Characato', 'Jacobo Hunter', 'José Luis Bustamante y Rivero', 'Mariano Melgar', 'Miraflores', 'Paucarpata', 'Sabandía', 'Sachaca', 'Socabaya', 'Tiabaya', 'Yanahuara', 'Yura', 'La Joya'], Camaná: ['Camaná', 'José María Quimper', 'Nicolás de Piérola', 'Samuel Pastor'], Caravelí: ['Caravelí', 'Acarí', 'Atico', 'Chala', 'Lomas'], Castilla: ['Aplao', 'Andagua', 'Huancarqui', 'Uraca', 'Viraco'], Caylloma: ['Chivay', 'Cabanaconde', 'Majes', 'Yanque'], Condesuyos: ['Chuquibamba', 'Andaray', 'Yanaquihua'], Islay: ['Mollendo', 'Cocachacra', 'Islay', 'Mejia', 'Punta de Bombón'], 'La Unión': ['Cotahuasi', 'Alca', 'Puyca', 'Toro'] },
  Ayacucho: { Huamanga: ['Ayacucho', 'Carmen Alto', 'Jesús Nazareno', 'San Juan Bautista'], Cangallo: ['Cangallo', 'Chuschi', 'Los Morochucos'], 'Huanca Sancos': ['Sancos', 'Carapo', 'Sacsamarca'], Huanta: ['Huanta', 'Llochegua', 'Sivia'], 'La Mar': ['San Miguel', 'Anco', 'Ayna', 'Tambos'], Lucanas: ['Puquio', 'Chaviña', 'Sancos'], Parinacochas: ['Coracora', 'Chumpi', 'Pullo'], 'Paucar del Sara Sara': ['Pausa', 'Lampa', 'Oyolo'], Sucre: ['Querobamba', 'Belén', 'San Salvador'], 'Víctor Fajardo': ['Huancapi', 'Alcamenca', 'Huamanquiquia'], 'Vilcas Huamán': ['Vilcas Huamán', 'Concepción', 'Vischongo'] },
  Cajamarca: { Cajamarca: ['Cajamarca', 'Baños del Inca', 'Encañada', 'Namora'], Cajabamba: ['Cajabamba', 'Condebamba', 'SitaCocha'], Celendín: ['Celendín', 'Huasmin', 'Sorochuco'], Chota: ['Chota', 'Huambos', 'Llama', 'Paccha'], Contumazá: ['Contumazá', 'Chilete', 'Yonán'], Cutervo: ['Cutervo', 'Querocotillo', 'Santo Domingo'], Hualgayoc: ['Bambamarca', 'Chugur', 'Hualgayoc'], Jaén: ['Jaén', 'Bellavista', 'Pucará', 'Santa Rosa'], 'San Ignacio': ['San Ignacio', 'Chirinos', 'Namballe'], 'San Marcos': ['Pedro Gálvez', 'Chancay', 'Ichocán'], 'San Miguel': ['San Miguel', 'Calquis', 'Llapa'], 'San Pablo': ['San Pablo', 'San Bernardino', 'Tumbaden'], 'Santa Cruz': ['Santa Cruz', 'Catache', 'Chancaybaños'] },
  Callao: { Callao: ['Callao', 'Bellavista', 'Carmen de la Legua', 'La Perla', 'La Punta', 'Ventanilla', 'Mi Perú'] },
  Cusco: { Cusco: ['Cusco', 'Ccorca', 'Poroy', 'San Jerónimo', 'San Sebastián', 'Santiago', 'Saylla', 'Wanchaq'], Acomayo: ['Acomayo', 'Acopia', 'Acos', 'Mosoc Llacta', 'Pomacanchi', 'Rondocan', 'Sangarará'], Anta: ['Anta', 'Ancahuasi', 'Cachimayo', 'Chinchaypujio', 'Huarocondo', 'Limatambo', 'Mollepata', 'Pucyura', 'Zurite'], Calca: ['Calca', 'Coya', 'Lamay', 'Lares', 'Pisac', 'San Salvador', 'Taray', 'Yanatile'], Canas: ['Yanaoca', 'Checca', 'Kunturkanki', 'Langui', 'Layo', 'Pampamarca', 'Quehue', 'Túpac Amaru'], Canchis: ['Sicuani', 'Checacupe', 'Combapata', 'Maranganí', 'Pitumarca', 'San Pablo', 'San Pedro', 'Tinta'], Chumbivilcas: ['Santo Tomás', 'Capacmarca', 'Chamaca', 'Colquemarca', 'Livitaca', 'Llusco', 'Quiñota', 'Velille'], Espinar: ['Espinar', 'Condoroma', 'Coporaque', 'Ocoruro', 'Pallpata', 'Pichigua', 'Suyckutambo', 'Alto Pichigua'], 'La Convención': ['Santa Ana', 'Echarate', 'Huayopata', 'Maranura', 'Ocobamba', 'Quellouno', 'Kimbiri', 'Santa Teresa', 'Vilcabamba', 'Pichari', 'Inkawasi', 'Villa Virgen', 'Villa Kintiarina', 'Megantoni'], Paruro: ['Paruro', 'Accha', 'Ccapi', 'Colcha', 'Huanoquite', 'Omacha', 'Paccaritambo', 'Pillpinto', 'Yaurisque'], Paucartambo: ['Paucartambo', 'Caicay', 'Challabamba', 'Colquepata', 'Huancarani', 'Kosñipata'], Quispicanchi: ['Urcos', 'Andahuaylillas', 'Camanti', 'Ccarhuayo', 'Ccatca', 'Cusipata', 'Huaro', 'Lucre', 'Marcapata', 'Ocongate', 'Oropesa', 'Quiquijana'], Urubamba: ['Urubamba', 'Chinchero', 'Huayllabamba', 'Machupicchu', 'Maras', 'Ollantaytambo', 'Yucay'] },
  Huancavelica: { Huancavelica: ['Huancavelica', 'Ascensión', 'Yauli'], Acobamba: ['Acobamba', 'Andabamba', 'Paucará'], Angaraes: ['Lircay', 'Congalla', 'Julcamarca'], Castrovirreyna: ['Castrovirreyna', 'Ticrapo', 'Cocas'], Churcampa: ['Churcampa', 'Anco', 'Paucarbamba'], Huaytará: ['Huaytará', 'Ayaví', 'Pilpichaca'], Tayacaja: ['Pampas', 'Acraquia', 'Colcabamba'] },
  Huánuco: { Huánuco: ['Huánuco', 'Amarilis', 'Pillco Marca', 'Santa María del Valle'], Ambo: ['Ambo', 'Huácar', 'San Rafael'], 'Dos de Mayo': ['La Unión', 'Ripán', 'Sillapata'], Huacaybamba: ['Huacaybamba', 'Canchabamba'], Huamalíes: ['Llata', 'Monzón', 'Puños'], 'Leoncio Prado': ['Rupa-Rupa (Tingo María)', 'Castillo Grande', 'Luyando'], Marañón: ['Huacrachuco', 'Cholón'], Pachitea: ['Panao', 'Chaglla', 'Molino'], 'Puerto Inca': ['Puerto Inca', 'Yuyapichis'], Lauricocha: ['Jesús', 'Baños', 'Queropalca'], Yarowilca: ['Chavinillo', 'Aparicio Pomares'] },
  Ica: { Ica: ['Ica', 'La Tinguiña', 'Parcona', 'Subtanjalla'], Chincha: ['Chincha Alta', 'Chincha Baja', 'Pueblo Nuevo', 'Sunampe'], Nasca: ['Nasca', 'Changuillo', 'Marcona'], Palpa: ['Palpa', 'Llipata', 'Santa Cruz'], Pisco: ['Pisco', 'Humay', 'Paracas', 'San Andrés'] },
  Junín: { Huancayo: ['Huancayo', 'Chilca', 'El Tambo', 'Pilcomayo', 'Sapallanga'], Concepción: ['Concepción', 'Matahuasi', 'Orcotuna'], Chanchamayo: ['Chanchamayo', 'Perené', 'Pichanaqui', 'San Ramón'], Jauja: ['Jauja', 'Apata', 'Muquiyauyo'], Junín: ['Junín', 'Carhuamayo', 'Ondores'], Satipo: ['Satipo', 'Mazamari', 'Pangoa', 'Río Negro'], Tarma: ['Tarma', 'Acobamba', 'Palca'], Yauli: ['La Oroya', 'Morococha', 'Santa Rosa de Sacco'], Chupaca: ['Chupaca', 'Ahuac', 'Huachac'] },
  'La Libertad': { Trujillo: ['Trujillo', 'El Porvenir', 'Huanchaco', 'La Esperanza', 'Moche', 'Victor Larco'], Ascope: ['Ascope', 'Casa Grande', 'Chicama', 'Paiján'], Bolívar: ['Bolívar', 'Bambamarca', 'Uchumarca'], Chepén: ['Chepén', 'Pacanga', 'Pueblo Nuevo'], Julcán: ['Julcán', 'Calamarca'], Otuzco: ['Otuzco', 'Agallpampa', 'Usquil'], Pacasmayo: ['San Pedro de Lloc', 'Guadalupe', 'Pacasmayo'], Pataz: ['Tayabamba', 'Huancaspata', 'Pataz'], 'Sánchez Carrión': ['Huamachuco', 'Chugay', 'Sarin'], 'Santiago de Chuco': ['Santiago de Chuco', 'Angasmarca', 'Quiruvilca'], 'Gran Chimú': ['Cascas', 'Lucma', 'Sayapullo'], Virú: ['Virú', 'Chao', 'Guadalupito'] },
  Lambayeque: { Chiclayo: ['Chiclayo', 'José Leonardo Ortiz', 'La Victoria', 'Pimentel', 'Reque', 'Santa Rosa'], Lambayeque: ['Lambayeque', 'Illimo', 'Mochumí', 'Mórrope', 'Motupe', 'Olmos', 'Túcume'], Ferreñafe: ['Ferreñafe', 'Cañaris', 'Incahuasi', 'Manuel Antonio Mesones Muro', 'Pueblo Nuevo', 'Tres Tomas'] },
  Lima: { Lima: ['Lima', 'Ancón', 'Ate', 'Barranco', 'Breña', 'Carabayllo', 'Chaclacayo', 'Chorrillos', 'Cieneguilla', 'Comas', 'El Agustino', 'Independencia', 'Jesús María', 'La Molina', 'La Victoria', 'Lince', 'Los Olivos', 'Lurigancho', 'Lurín', 'Magdalena del Mar', 'Miraflores', 'Pachacámac', 'Pucusana', 'Pueblo Libre', 'Puente Piedra', 'Punta Hermosa', 'Punta Negra', 'Rímac', 'San Bartolo', 'San Borja', 'San Isidro', 'San Juan de Lurigancho', 'San Juan de Miraflores', 'San Luis', 'San Martín de Porres', 'San Miguel', 'Santa Anita', 'Santa María del Mar', 'Santa Rosa', 'Santiago de Surco', 'Surquillo', 'Villa El Salvador', 'Villa María del Triunfo'], Barranca: ['Barranca', 'Paramonga', 'Pativilca', 'Supe', 'Supe Puerto'], Cajatambo: ['Cajatambo', 'Copa', 'Gorgor', 'Huancapón', 'Manás'], Canta: ['Canta', 'Arahuay', 'Huamantanga', 'Huaros', 'Lachaqui', 'San Buenaventura', 'Santa Rosa de Quives'], Cañete: ['San Vicente de Cañete', 'Asia', 'Calango', 'Cerro Azul', 'Chilca', 'Coayllo', 'Imperial', 'Lunahuaná', 'Mala', 'Nuevo Imperial', 'Pacarán', 'Quilmana', 'San Antonio', 'San Luis', 'Santa Cruz de Flores', 'Zúñiga'], Huaral: ['Huaral', 'Atavillos Alto', 'Atavillos Bajo', 'Aucallama', 'Chancay', 'Ihuarí', 'Lampian', 'Pacaraos', 'San Miguel de Acos', 'Santa Cruz de Andamarca', 'Sumbilca', 'Veintisiete de Noviembre'], Huarochirí: ['Matucana', 'Antioquía', 'Callahuanca', 'Carampoma', 'Chicla', 'Cuenca', 'Huachupampa', 'Huanza', 'Huarochirí', 'Lahuaytambo', 'Langa', 'Laraos', 'Mariatana', 'Ricardo Palma', 'San Andrés de Tupicocha', 'San Antonio', 'San Bartolomé', 'San Damián', 'San Juan de Iris', 'San Juan de Tantaranche', 'San Lorenzo de Quinti', 'San Mateo', 'San Mateo de Otao', 'San Pedro de Casta', 'San Pedro de Huancayre', 'Sangallaya', 'Santa Cruz de Cocachacra', 'Santa Eulalia', 'Santiago de Anchucaya', 'Santiago de Tuna', 'Santo Domingo de los Olleros', 'Surco'], Huaura: ['Huacho', 'Ámbar', 'Caleta de Carquín', 'Checras', 'Hualmay', 'Huaura', 'Leoncio Prado', 'Paccho', 'Santa Leonor', 'Santa María', 'Sayán', 'Végueta'], Oyón: ['Oyón', 'Andajes', 'Caujul', 'Cochamarca', 'Naván', 'Pachangara'], Yauyos: ['Yauyos', 'Alis', 'Allauca', 'Ayauca', 'Ayavirí', 'Azángaro', 'Cacra', 'Carania', 'Catahuasi', 'Chocos', 'Cochas', 'Colonia', 'Hongos', 'Huampará', 'Huancaya', 'Huangáscar', 'Huántan', 'Huañec', 'Laraos', 'Lincha', 'Madean', 'Miraflores', 'Omas', 'Putinza', 'Quinches', 'Quinocay', 'San Joaquín', 'San Pedro de Pilas', 'Tanta', 'Tauripampa', 'Tomas', 'Tupe', 'Viñac', 'Vitis'] },
  Loreto: { Maynas: ['Iquitos', 'Belén', 'Punchana', 'San Juan Bautista'], 'Alto Amazonas': ['Yurimaguas', 'Balsapuerto', 'Lagunas'], Loreto: ['Nauta', 'Parinari', 'Tigre'], 'Mariscal Ramón Castilla': ['Caballococha', 'Pebas', 'Yavarí'], Requena: ['Requena', 'Jenaro Herrera', 'Sapuena'], Ucayali: ['Contamana', 'Inahuaya', 'Pampa Hermosa'], 'Datem del Marañón': ['San Lorenzo', 'Andoas', 'Barranca'], Putumayo: ['San Antonio del Estrecho', 'Teniente Manuel Clavero'] },
  'Madre de Dios': { Tambopata: ['Puerto Maldonado', 'Inambari', 'Laberinto'], Manu: ['Manu', 'Fitzcarrald', 'Huepetuhe'], Tahuamanu: ['Iñapari', 'Iberia', 'Tahuamanu'] },
  Moquegua: { 'Mariscal Nieto': ['Moquegua', 'Samegua', 'Torata'], 'General Sánchez Cerro': ['Omate', 'Puquina', 'Ubinas'], Ilo: ['Ilo', 'El Algarrobal', 'Pacocha'] },
  Pasco: { Pasco: ['Chaupimarca', 'Huayllay', 'Yanacancha'], 'Daniel Alcides Carrión': ['Yanahuanca', 'Chacayán', 'Paucar'], Oxapampa: ['Oxapampa', 'Chontabamba', 'Pozuzo', 'Villa Rica'] },
  Piura: { Piura: ['Piura', 'Castilla', 'Catacaos', 'Tambo Grande', 'Veintiséis de Octubre'], Ayabaca: ['Ayabaca', 'Frías', 'Pacaipampa'], Huancabamba: ['Huancabamba', 'Canchaque', 'Sondor'], Morropón: ['Chulucanas', 'Morropón', 'Salitral'], Paita: ['Paita', 'Colán', 'Vichayal'], Sullana: ['Sullana', 'Bellavista', 'Marcavelica', 'Querecotillo'], Talara: ['Pariñas', 'El Alto', 'Los Órganos', 'Máncora'], Sechura: ['Sechura', 'Bernal', 'Vice'] },
  Puno: { Puno: ['Puno', 'Acora', 'Amantani', 'Atuncolla', 'Capachica', 'Chucuito', 'Coata', 'Huata', 'Mañazo', 'Paucarcolla', 'Pichacani', 'Plateria', 'San Antonio', 'Tiquillaca', 'Vilque'], Azángaro: ['Azángaro', 'Achaya', 'Arapa', 'Asillo', 'Caminaca', 'Chupa', 'José Domingo Choquehuanca', 'Muñani', 'Potoni', 'Saman', 'San Antón', 'San José', 'San Juan de Salinas', 'Santiago de Pupuja', 'Tirapata'], Carabaya: ['Macusani', 'Ajoyani', 'Ayapata', 'Coasa', 'Corani', 'Crucero', 'Ituata', 'Ollachea', 'San Gabán', 'Usicayos'], Chucuito: ['Juli', 'Desaguadero', 'Huacullani', 'Kelluyo', 'Pisacoma', 'Pomata', 'Zepita'], 'El Collao': ['Ilave', 'Capazo', 'Pilcuyo', 'Santa Rosa', 'Conduriri'], Huancané: ['Huancané', 'Cojata', 'Huatasani', 'Inchupalla', 'Pusi', 'Rosaspata', 'Taraco', 'Vilque Chico'], Lampa: ['Lampa', 'Cabanilla', 'Calapuja', 'Nicasio', 'Ocuviri', 'Palca', 'Paratia', 'Pucará', 'Santa Lucía', 'Vilavila'], Melgar: ['Ayaviri', 'Antauta', 'Cupi', 'Llalli', 'Macari', 'Nuñoa', 'Orurillo', 'Santa Rosa', 'Umachiri'], Moho: ['Moho', 'Conima', 'Huayrapata', 'Tilali'], 'San Antonio de Putina': ['Putina', 'Ananea', 'Pedro Vilca Apaza', 'Quilcapuncu', 'Sina'], 'San Román': ['Juliaca', 'Cabana', 'Cabanillas', 'Caracoto', 'San Miguel'], Sandia: ['Sandia', 'Alto Inambari', 'Cuyocuyo', 'Limbani', 'Patambuco', 'Phara', 'Quiaca', 'San Juan del Oro', 'San Pedro de Putina Punco', 'Yanahuaya'], Yunguyo: ['Yunguyo', 'Anapia', 'Copani', 'Cuturapi', 'Ollaraya', 'Tinicachi', 'Unicachi'] },
  'San Martín': { Moyobamba: ['Moyobamba', 'Jepelacio', 'Soritor'], Bellavista: ['Bellavista', 'Bajo Biavo'], 'El Dorado': ['San José de Sisa', 'Shatoja'], Huallaga: ['Saposoa', 'Piscoyacu'], Lamas: ['Lamas', 'Caynarachi', 'Tabalosos'], 'Mariscal Cáceres': ['Juanjuí', 'Pachiza'], Picota: ['Picota', 'Caspisapa'], Rioja: ['Rioja', 'Nueva Cajamarca', 'Pardo Miguel'], 'San Martín': ['Tarapoto', 'Morales', 'La Banda de Shilcayo'], Tocache: ['Tocache', 'Pólvora', 'Uchiza'] },
  Tacna: { Tacna: ['Tacna', 'Alto de la Alianza', 'Ciudad Nueva', 'Gregorio Albarracín'], Candarave: ['Candarave', 'Curibaya'], 'Jorge Basadre': ['Locumba', 'Ite'], Tarata: ['Tarata', 'Estique', 'Ticaco'] },
  Tumbes: { Tumbes: ['Tumbes', 'Corrales', 'La Cruz', 'Pampas de Hospital'], 'Contralmirante Villar': ['Zorritos', 'Casitas'], Zarumilla: ['Zarumilla', 'Aguas Verdes', 'Papayal'] },
  Ucayali: { 'Coronel Portillo': ['Pucallpa', 'Manantay', 'Yarinacocha'], Atalaya: ['Atalaya', 'Sepahua'], 'Padre Abad': ['Aguaytía', 'Curimaná', 'Irazola'], Purús: ['Esperanza'] }
}
